version: 2.0
jobs:
  build:
    working_directory: ~/tenqmemo
    docker:
      - image: talktome/tenqmemo:latest
      - image: redis:3.0.7-alpine
      - image: postgres:9.6.2
        environment:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
          POSTGRES_DB: tenqmemo_test
    environment:
      NODE_ENV: development
      RAILS_ENV: test
      RACK_ENV: test
      YARN_VERSION: 0.21.3
      REDIS_URL: redis://127.0.0.1:6379/0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfile-{{ checksum "Gemfile.lock" }}
            - packagejson-{{ checksum "package.json" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: packagejson-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: npm run build
          command: npm run build
      - run:
          name: create database
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: migration database
          command: bundle exec rails db:migrate
      - run:
          name: ruby test
          command: bundle exec rails test
      - run:
          name: js test
          command: npm test
      - store_artifacts:
          path: log/test.log
          destination: test.log
