version: 2.0
jobs:
  build:
    working_directory: ~/tenqmemo
    docker:
      - image: talktome/tenqmemo:latest
      - image: redis:3.0.7-alpine
      - image: postgres:9.6.2
        environment:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
          POSTGRES_DB: tenqmemo_test
    environment:
      NODE_ENV: development
      RAILS_ENV: test
      RACK_ENV: test
      YARN_VERSION: 0.21.3
      REDIS_URL: redis://127.0.0.1:6379/0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfile-2.4-{{ .Branch }}-
            - gemfile-2.4-master
      - restore_cache:
          keys:
            - npm-3.10-{{ .Branch }}-
            - npm-3.10-master
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle -j 36
      - save_cache:
          key: gemfile-2.4-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: npm-3.10-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: yarn run build
          command: yarn run build
      - run:
          name: create database
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: migration database
          command: bundle exec rails db:migrate
      - run:
          name: unit test
          command: bundle exec rails test
      - run:
          name: system test
          command: bundle exec rails test:system
      - run:
          name: js test
          command: yarn test ---reporter mocha-junit-reporter ---reporter-options mochaFile=tmp/test_reports/mocha/result.xml
      - store_test_results:
          path: tmp/test_reports
      - store_artifacts:
          path: log/test.log
          destination: test.log
