version: 2.0
jobs:
  build:
    working_directory: /root/tenqmemo
    docker:
      - image: talktome/tenqmemo:latest
      - image: redis:3.0.7-alpine
      - image: postgres:9.6.2
        environment:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
          POSTGRES_DB: tenqmemo_test
    environment:
      NODE_ENV: development
      RAILS_ENV: test
      RACK_ENV: test
      YARN_VERSION: 0.21.3
      REDIS_URL: redis://127.0.0.1:6379/0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfile-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle -j 36
      - save_cache:
          key: gemfile-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: yarn install
          command: /root/.yarn/bin/yarn install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: yarn run build
          command: /root/.yarn/bin/yarn run build
      - run:
          name: create database
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: migration database
          command: bundle exec rails db:migrate
      - run:
          name: ruby test
          command: bundle exec rails test
      - run:
          name: js test
          command: /root/.yarn/bin/yarn test
      - store_test_results:
          path: tmp/test_reports
      - store_artifacts:
          path: log/test.log
          destination: test.log
